### ISSUE TITLE
TypeError: getRecordITC(...).getTypeNonNull is not a function

### ISSUE THREAD

**Issue by shanewilson** [graphql-compose/graphql-compose-elasticsearch#36]
Hey, just got this error trying to upgrade from 1.8.0 -> 1.10.0. After some investigating I noticed it actually appears between 1.9.0 -> 1.9.1. Which makes sense because this commit seems very relevant: https://github.com/graphql-compose/graphql-compose-elasticsearch/releases/tag/v1.9.1

```
.../graphql-compose-elasticsearch/lib/resolvers/updateById.js:60
    record: getRecordITC(fieldMap).getTypeNonNull()
                                   ^

TypeError: getRecordITC(...).getTypeNonNull is not a function
    at createUpdateByIdResolver (.../graphql-compose-elasticsearch/lib/resolvers/updateById.js:60:36)
    at composeWithElastic (.../graphql-compose-elasticsearch/lib/composeWithElastic.js:65:46)
    at _graphql.GraphQLSchema.query._graphql.GraphQLObjectType.fields.map.reduce (.../schema/index.js:22:34)
    at Array.reduce (<anonymous>)
    at Object.<anonymous> (.../schema/index.js:19:8)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Module._compile (.../pirates/lib/index.js:91:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.newLoader [as .js] (.../pirates/lib/index.js:96:7)
    at Module.load (internal/modules/cjs/loader.js:612:32)
```

I tried with the example in the README and still get this error. Not sure sure what I'm supposed to do to fix this so any help would be great.

Thanks

**Comment by nodkz** [comment]
It looks like you have several `graphql-compose` libs in your `node_modules` or used old `graphql-compose` version.

I made changes in package.json where placed proper valid minimal version 4.4.1 for graphql-compose in peerDependencies.

**Comment by shanewilson** [comment]
thanks - upgrading `graphql-compose` did fix this for me
