### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by emorneau** [graphql-compose/graphql-compose-elasticsearch#43]
Any help would be great!
node -v
v10.0.0

[nodemon] starting `./node_modules/.bin/babel-node ./examples/elastic50/index.js`
/Users/emorneau/git/graphql-compose-elasticsearch/node_modules/@babel/helper-plugin-utils/lib/index.js:72
  throw Object.assign(err, {
  ^

Error: Requires Babel "^7.0.0-0", but was loaded with "6.24.1". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/Users/emorneau/git/graphql-compose-elasticsearch/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/Users/emorneau/git/graphql-compose-elasticsearch/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at _default (/Users/emorneau/git/graphql-compose-elasticsearch/node_modules/@babel/plugin-proposal-object-rest-spread/lib/index.js:41:7)
    at /Users/emorneau/git/graphql-compose-elasticsearch/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (/Users/emorneau/git/graphql-compose-elasticsearch/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/Users/emorneau/git/graphql-compose-elasticsearch/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /Users/emorneau/git/graphql-compose-elasticsearch/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/emorneau/git/graphql-compose-elasticsearch/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/emorneau/git/graphql-compose-elasticsearch/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/emorneau/git/graphql-compose-elasticsearch/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at compile (/Users/emorneau/git/graphql-compose-elasticsearch/node_modules/babel-register/lib/node.js:103:45)
    at loader (/Users/emorneau/git/graphql-compose-elasticsearch/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/emorneau/git/graphql-compose-elasticsearch/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/emorneau/git/graphql-compose-elasticsearch/examples/elastic50/index.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Module._compile (/Users/emorneau/git/graphql-compose-elasticsearch/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Object.newLoader (/Users/emorneau/git/graphql-compose-elasticsearch/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:589:32)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by nodkz** [comment]
Try to remove `./node_modules` folder and reinstall all packages from scratch.
Better via yarn package manager.
