### ISSUE TITLE
TypeError: _graphqlCompose.TypeComposer is not a constructor

### ISSUE THREAD

**Issue by stiekel** [graphql-compose/graphql-compose-elasticsearch#71]
Code: 
```js
const graphqlCompose = require('graphql-compose');
const graphql = require('graphql');
const graphqlComposeElasticsearch = require('graphql-compose-elasticsearch');
const elasticsearch = require('elasticsearch');

const client = new elasticsearch.Client({
    host: 'http://x.x.x.x:9200',
    apiVersion: '5.6',
    log: 'trace'
});

const elasticMapping = {
    properties: {
        size: {
            type: 'long'
        },
        time: {
            type: 'long'
        }
    }
}

const Log = graphqlComposeElasticsearch.composeWithElastic({
    graphqlTypeName: 'Log',
    elasticIndex: 'log',
    elasticType: 'log',
    elasticMapping,
    elasticClient: client
});

const schema = new graphql.GraphQLSchema({
    query: new graphql.GraphQLObjectType({
        name: 'Query',
        fields: {
            elastic56: client,
            Log: Log.getResolver('search').getFieldConfig()
        }
    })
});

module.exports = schema;

```
Error:
```sh
Elasticsearch INFO: 2019-08-09T06:27:48Z
  Adding connection to http://x.x.x.x:9200/

/data/demo/node_modules/graphql-compose-elasticsearch/lib/mappingConverter.js:61
  var tc = new _graphqlCompose.TypeComposer(new _graphql.GraphQLObjectType({
           ^
TypeError: _graphqlCompose.TypeComposer is not a constructor
    at convertToSourceTC (/data/demo/node_modules/graphql-compose-elasticsearch/lib/mappingConverter.js:61:12)
    at Object.composeWithElastic (/data/demo/node_modules/graphql-compose-elasticsearch/lib/composeWithElastic.js:60:58)
    at Object.<anonymous> (/data/demo/app/mapping/Log.js:44:46)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/data/demo/app/mapping/index.js:1:18)
```

Node Version: 11.14.0
OS: CentOS
graphql: ^14.4.2
graphql-compose: ^7.3.0
graphql-compose-elasticsearch: ^1.10.1

**Comment by stiekel** [comment]
I use an old version of `graphql-compose-elasticsearch`, after updated to 4.0.4, this issue disappeared.
