### ISSUE TITLE
Mappings with hyphens can't be parsed

### ISSUE THREAD

**Issue by clintandrewhall** [graphql-compose/graphql-compose-elasticsearch#74]
If the ES mapping property name contains a hyphen, the service cannot start.  Is there a workaround?

```
    "comment-author-type": {
      type: "text",
      fields: {
        keyword: {
          type: "keyword",
          ignore_above: 256
        }
      }
    },
```
```
"errors": [
    {
      "message": "Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"comment-author-type\" does not.",
      "stack": [
        "GraphQLError: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"comment-author-type\" does not.",
        "    at isValidNameError (/Users/clint/Projects/chirp/node_modules/graphql/utilities/assertValidName.js:42:12)",
        "    at validateName (/Users/clint/Projects/chirp/node_modules/graphql/type/validate.js:199:53)",
        "    at validateInputFields (/Users/clint/Projects/chirp/node_modules/graphql/type/validate.js:439:5)",
        "    at validateTypes (/Users/clint/Projects/chirp/node_modules/graphql/type/validate.js:240:7)",
        "    at validateSchema (/Users/clint/Projects/chirp/node_modules/graphql/type/validate.js:54:3)",
        "    at /Users/clint/Projects/chirp/node_modules/express-graphql/index.js:97:66",
        "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
      ]
    },
```

**Comment by Zhouchuanwen** [comment]
same error
![image](https://user-images.githubusercontent.com/7982753/90750867-02890880-e308-11ea-94bf-53b822a715c1.png)
